In [1]:
import numpy as np
import pandas as pd

In [2]:
movies =pd.read_csv("tmdb_5000_movies.csv")
credits=pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
#  to merge the dataset

# name of one data .merge the name of other data and the column on the basis of which we are adding
movies = movies.merge(credits, on='title')
result_shape = movies.shape

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [8]:
movies=movies[['movie_id','title','overview','genres','cast','crew','keywords']]

In [9]:
movies.info

<bound method DataFrame.info of       movie_id                                     title  \
0        19995                                    Avatar
1          285  Pirates of the Caribbean: At World's End
2       206647                                   Spectre
3        49026                     The Dark Knight Rises
4        49529                               John Carter
...        ...                                       ...
4804      9367                               El Mariachi
4805     72766                                 Newlyweds
4806    231617                 Signed, Sealed, Delivered
4807    126186                          Shanghai Calling
4808     25975                         My Date with Drew

                                               overview  \
0     In the 22nd century, a paraplegic Marine is di...
1     Captain Barbossa, long believed to be dead, ha...
2     A cryptic message from Bond’s past sends him o...
3     Following the death of District Attorney Harve...
4     John Carter is a war-weary, former military ca...
...                                                 ...
4804  El Mariachi just wants to play his guitar and ...
4805  A newlywed couple's honeymoon is upended by th...
4806  "Signed, Sealed, Delivered" introduces a dedic...
4807  When ambitious New York attorney Sam is sent t...
4808  Ever since the second grade when he first saw ...

                                                 genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...
...                                                 ...
4804  [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                 []
4808                [{"id": 99, "name": "Documentary"}]

                                                   cast  \
0     [{"cast_id": 242, "character": "Jake Sully", "...
1     [{"cast_id": 4, "character": "Captain Jack Spa...
2     [{"cast_id": 1, "character": "James Bond", "cr...
3     [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4     [{"cast_id": 5, "character": "John Carter", "c...
...                                                 ...
4804  [{"cast_id": 1, "character": "El Mariachi", "c...
4805  [{"cast_id": 1, "character": "Buzzy", "credit_...
4806  [{"cast_id": 8, "character": "Oliver O\u2019To...
4807  [{"cast_id": 3, "character": "Sam", "credit_id...
4808  [{"cast_id": 3, "character": "Herself", "credi...

                                                   crew  \
0     [{"credit_id": "52fe48009251416c750aca23", "de...
1     [{"credit_id": "52fe4232c3a36847f800b579", "de...
2     [{"credit_id": "54805967c3a36829b5002c41", "de...
3     [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4     [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
...                                                 ...
4804  [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805  [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806  [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807  [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808  [{"credit_id": "58ce021b9251415a390165d9", "de...

                                               keywords
0     [{"id": 1463, "name": "culture clash"}, {"id":...
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...
4     [{"id": 818, "name": "based on novel"}, {"id":...
...                                                 ...
4804  [{"id": 5616, "name": "united states\u2013mexi...
4805                                                 []
4806  [{"id": 248, "name": "date"}, {"id": 699, "nam...
4807                                                 []
4808  [{"id": 1523, "name": "obsession"}, {"id": 224...

[4809 rows x 7 columns]>

In [10]:
movies.head()

,movie_id,title,overview,genres,cast,crew,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":..."

In [11]:
# tags will contain al other than title and id
# will add the genres, overview, cast, crew and keywords.
# for that we need to do some preprocessing

In [12]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
cast        0
crew        0
keywords    0
dtype: int64

In [13]:
movies = movies.copy()
movies.dropna(inplace=True) #it will remove all the null data

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
# we are getting improper list from the genre so we need to process it in such a way that we can get all the name of genres in one list
import ast  # No longer needed, but kept for clarity

def convert(obj):
    
    """Extracts genre names from lists or individual strings."""
    if isinstance(obj, list):  # Check if it's already a list
        return obj
    else:
        L=[] 
        for i in ast.literal_eval(obj):
            L.append(i['name'])
        return L
        
#         return ast.literal_eval(obj)  # Handle cases where it's a string

movies['genres'] = movies['genres'].apply(convert)

In [16]:
def convertk(obj):
    """Extracts genre names from nested lists or individual strings."""
    if isinstance(obj, list):
        # Recursively process each element in the list
        l_key = []
        for item in obj:
            if isinstance(item, dict):
                l_key.append(item['name'])
            else:
                # Handle nested lists if needed (example here)
                sub_genres = convert(item)
                if sub_genres:
                    l_key.extend(sub_genres)
        return l_key
    else:
        # Try converting a single string to a dictionary (if applicable)
        try:
            dict_obj = ast.literal_eval(obj)
            return [dict_obj['name']]
        except (ValueError, SyntaxError):
            return []  # Return empty list if conversion fails

# Apply the function
movies['keywords'] = movies['keywords'].apply(convert)

In [17]:
movies.head()

,movie_id,title,overview,genres,cast,crew,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[based on novel, mars, medallion, space travel..."

In [18]:
# we are getting improper list from the genre so we need to process it in such a way that we can get all the name of genres in one list
import ast  # No longer needed, but kept for clarity

def convert3(obj):
    
    """Extracts genre names from lists or individual strings."""
    if isinstance(obj, list):  # Check if it's already a list
        return obj
    else:
        L=[] 
        counter=0
        for i in ast.literal_eval(obj):
            if counter !=3:
                L.append(i['name'])
                counter+=1
            else:
                break
        return L
        
#         return ast.literal_eval(obj)  # Handle cases where it's a string
movies['cast'] = movies['cast'].apply(convert3)

In [19]:
movies.head()

,movie_id,title,overview,genres,cast,crew,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...","[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...","[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...","[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...","[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...","[based on novel, mars, medallion, space travel..."

In [20]:
# to fetch the director name
def fetch_director(obj):
    
    """Extracts genre names from lists or individual strings."""
    if isinstance(obj, list):  # Check if it's already a list
        return obj
    else:
        L=[] 
        for i in ast.literal_eval(obj):
            if i['job']=='Director':
                L.append(i['name'])
                break

        return L
        
#         return ast.literal_eval(obj)  # Handle cases where it's a string
movies['crew'] = movies['crew'].apply(fetch_director)

In [21]:
movies.head()

,movie_id,title,overview,genres,cast,crew,keywords
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[based on novel, mars, medallion, space travel..."

In [22]:
# to convert the overview which is in string to list
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [23]:
# need to apply a tanformation to remove the space in between and use the camelcase
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
# movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

movies.head()

,movie_id,title,overview,genres,cast,crew,keywords
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p..."

In [24]:
# need to create tag to concatenate overview, genres, keywords, cast, crew
# movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

# Convert lists to strings before concatenating to get rid of multiple commas and others
def list_to_str(lst):
    if isinstance(lst, list):
        return ' '.join(lst)
    return str(lst)

# it was used because after concatenating there we used to get ( ,, and '''''')
movies['tags'] = (
    movies['overview'].apply(list_to_str) +
    movies['genres'].apply(list_to_str) +
    movies['keywords'].apply(list_to_str) +
    movies['cast'].apply(list_to_str) +
    movies['crew'].apply(list_to_str)
)

# Display the 'tags' column for the first row
print(movies['tags'][0])

In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.Action Adventure Fantasy ScienceFictioncultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3dSamWorthington ZoeSaldana SigourneyWeaverJamesCameron

In [25]:
print(movies['tags'][1])

Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.Adventure Fantasy Actionocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstingerJohnnyDepp OrlandoBloom KeiraKnightleyGoreVerbinski

In [26]:
# need to vectorise the tag as we some words which is common or have good frequency and based on that we will recommend the movie
 #as we dont need stop words like is are am , in, the and the mxt word count we will need is 5000 to have better accuracy
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [27]:
vectors= cv.fit_transform(movies['tags']).toarray()
# print(vectors[0])

In [28]:
# to get the name or data of the corpus
feature_names = cv.get_feature_names_out()
print(feature_names)

['000' '007' '10' ... 'zombies' 'zone' 'zoo']

In [29]:
# if we will have multiple form of same name then it will cause issue like 'loves','loving', 'loved'
# to solve this issue we need nltk

!pip install nltk

Requirement already satisfied: nltk in c:\users\win10\appdata\local\programs\python\python39\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\win10\appdata\local\programs\python\python39\lib\site-packages (from nltk) (8.0.3)
Requirement already satisfied: joblib in c:\users\win10\appdata\local\programs\python\python39\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\win10\appdata\local\programs\python\python39\lib\site-packages (from nltk) (2023.12.25)
Requirement already satisfied: tqdm in c:\users\win10\appdata\local\programs\python\python39\lib\site-packages (from nltk) (4.66.1)
Requirement already satisfied: colorama in c:\users\win10\appdata\local\programs\python\python39\lib\site-packages (from click->nltk) (0.4.4)

WARNING: Ignoring invalid distribution -illow (c:\users\win10\appdata\local\programs\python\python39\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\win10\appdata\local\programs\python\python39\lib\site-packages)

In [30]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [31]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [32]:
stem('Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.Adventure Fantasy Actionocean drugabuse exoticisland eastindiatradingcompany loveofone slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstingerJohnnyDepp OrlandoBloom KeiraKnightleyGoreVerbinski')

'captain barbossa, long believ to be dead, ha come back to life and is head to the edg of the earth with will turner and elizabeth swann. but noth is quit as it seems.adventur fantasi actionocean drugabus exoticisland eastindiatradingcompani loveofon slife traitor shipwreck strongwoman ship allianc calypso afterlif fighter pirat swashbuckl aftercreditsstingerjohnnydepp orlandobloom keiraknightleygoreverbinski'

In [33]:
movies['tags']= movies['tags'].apply(stem)
print(movies['tags'])

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [34]:
#  we need to calculate distance between each movie, more the distance less the similarity
#  we will not cal euclidian dist instead we cal angle between them(cosine dis) less the angle more the similarity
#  euclidian distance is  not reliable for highre dimension

from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [35]:
similarity[0]

array([1.        , 0.06963106, 0.06700252, ..., 0.02594996, 0.02787473,
       0.        ])

In [36]:
# we need to give the most five similar movie
# for this we can take the movie as an input and will go into the matric and will fetch the index of that movie
# after that we can take the five most similar movie with higher similarity can be taken

def recommend_movie(movie):
    movie_index=movies[movies['title']==movie].index[0]
    distances=similarity[movie_index]
    movie_list=sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6] #it will give the tuple of required movies relation with other movies as movie_name and similarity
    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [37]:
recommend_movie('Spectre')

Never Say Never Again
Quantum of Solace
Skyfall
Thunderball
Die Another Day

In [38]:
 import pickle

In [40]:
pickle.dump(movies.to_dict(), open('movies_dict.pkl','wb'))

In [42]:
pickle.dump(similarity, open('similarity.pkl','wb'))